### PR TITLE
MM-12985 Add logic to test post metadata

### PR DESCRIPTION
**Pull request by hmhealey**
This makes it so that:
1. When a post has metadata, the agent will not make followup requests for data that is included in that
2. Instead of randomly requesting custom emojis or opengraph data when receiving a post, those are now added onto the post when it is created to trigger a server to send down that metadata

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12985

### CODE REVIEW

**Comment by hmhealey** [comment]
I've marked this as Work In Progress because I don't seem to be able to update the version of mattermost-server in gopkg.lock until 5.6 is shipped

**Review by lieut-data — APPROVED** [review]
Looks good to me! Can you push an update to https://github.com/mattermost/mattermost-load-test/pull/131 to document `CustomEmojiReactionChance` and `SystemEmojiReactionChance`?

**Review by jwilander — APPROVED** [review]
LGTM

**Comment by hmhealey** [comment]
@lieut-data This is probably going to need to wait for 5.6 to be cut so I can upgrade the mattermost-server dependency, so I think it might make more sense if I rebase this PR on top of you changes once they go in

**Comment by lieut-data** [comment]
@hmhealey, should we just close this one out for now?

**Comment by hmhealey** [comment]
I'll see if I can get it to build by updating the dependencies since that should be the only thing blocking it

**Comment by hmhealey** [comment]
@cpanato Any idea what's causing this build to fail? It says it can't find `dep`, but the path it's using also seems kind of mangled

**Comment by lieut-data** [comment]
@hmhealey, I think the build is known to be broken -- if it builds and runs locally after merging `master`, we usually merge it as-is right now.

**Comment by cpanato** [comment]
@hmhealey @lieut-data we used to have in the makefile the `go get -u github.com/golang/dep/cmd/dep` but looks like was removed here: https://github.com/mattermost/mattermost-load-test/commit/cac157e961a893c5c23d15c1a42a73f26f55666e

can we add back?

**Comment by lieut-data** [comment]
@cpanato, I think so? I don't recall what the issue was that prompted us to remove it in the first place.

**Comment by cpanato** [comment]
or we add in the pipeline to download

**Comment by hanzei** [comment]
What is the status on this PR? Can it be merged after a rebase?

**Comment by lieut-data** [comment]
@hmhealey / @grundleborg, heads up that I've gone ahead and merged this one. The alternative was to close, I think, but I'm guessing we're better off with this behaviour merged and testable.

**Pull request merged**
