### PR TITLE
Distribute entity actions over time instead of front-loading them

### PR DESCRIPTION
**Pull request by ccbrown**
This gets rid of the regular spikes in CPU usage. When the load tests began, every entity would act immediately. Then 4 minutes later, every entity would act again. Then 4 minutes later, again, and so on. They didn't act at exactly the same time because they don't all start at exactly the same time (and there's a slight variance applied), but the activity was always very front-loaded.

This should have a pretty positive impact on our load test performance, but probably more importantly, this allows us to get much more consistent and accurate profiles.

### CODE REVIEW

**Comment by crspeller** [comment]
Shouldn't https://github.com/mattermost/mattermost-load-test/blob/master/loadtest/run.go#L144 be distributing them?

**Comment by ccbrown** [comment]
Hm. I hadn't noticed that sleep. Yeah that seems like it should more or less do it... (ignoring the drift due to connection time in that loop). But I know it's not. I need to dig deeper apparently to figure out exactly why...

**Comment by ccbrown** [comment]
@crspeller Yeah, so that sleep isn't distributing them because it doesn't account for multiple entity types. For example, if you run a test with 20,000 entities, 2,000 of those entities will be "webhook user" entities. And all of those entities will be created consecutively, in a tight grouping.

Those entities only create posts. So when its their turn to act, we see this (from a short profile during the CPU spike):

screen shot 2018-02-26 at 11 39 46 pm

(`GetAllProfilesInChannel` is only called when posts are made.)

**Comment by crspeller** [comment]
@ccbrown Ah right. That makes sense, can we as part of this PR remove the old method of distribution so it's not confusing?

**Comment by ccbrown** [comment]
Do you think we can just remove the sleep entirely? I wouldn't want to overload the server before the tests even begin. (I haven't tested it, but it seems like it might be a good idea to leave some sort of pacing in.)

**Comment by crspeller** [comment]
Ya probably better to leave it in.

**Pull request merged**
