### PR TITLE
MM-10485 Add profile image pulling on channel switch

### PR DESCRIPTION
**Pull request by jwilander**
https://mattermost.atlassian.net/browse/MM-10485

Still need to run an actual load test with it but having issues with the bulk importer

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Review by lieut-data — APPROVED** [review]

**Comment by jwilander** [comment]
Running a load test on this is blocked by https://mattermost.atlassian.net/browse/MM-11119

**Comment by hanzei** [comment]
https://mattermost.atlassian.net/browse/MM-11119 got fixed. What is the status on this one? Can we run a load test now?

**Comment by jwilander** [comment]
We'd need to rebase this and run a load test to try it out but it's not really a priority at the moment

**Comment by hanzei** [comment]
@cpanato Not sure what's up with the build. Could you please take a look?

**Pull request closed without merging**
